##  Name of the workflow
name: TechTrends - Package with Docker
## Set the trigger policy.
## In this case, the workflow is execute on a `push` event,
## or when a new commit is pushed to the repository
on: 
  push
  branches:
      - 'main'

## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  publish-to-docker:
    ## Configure the operating system the workflow should run on.
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ## Use the public `checkout` actoin  in version v2  
      ## to checkout the existing code in the repository
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: project
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: sjaindl/techtrends:latest
